### ISSUE TITLE
tar-ball on pypi

### ISSUE THREAD

**Issue by arunpersaud** [bigsassy/pytest-pythonpath#12]
could you upload the tar-ball to pypi (including the license)? This would make packaging for linux distributions easier (hard to update the opensuse package at the moment). Thanks.

**Comment by bigsassy** [comment]
Sure thing.  I'll try to get this done sometime today.  Feel free to bug me again if it's not done by tomorrow.

**Comment by arunpersaud** [comment]
great. Thanks

**Comment by bigsassy** [comment]
Sorry for the delay, everyone.  And thank you to @nelson-liu for PR #13 🎉.  I've also bumped the version to 0.7.3 and tagged the release.

I believe everything is taken care of at this point.  Let me know if there are any issues.
