### ISSUE TITLE
Support pytest 7.x

### ISSUE THREAD

**Issue by PhilippSelenium** [bigsassy/pytest-pythonpath#18]
https://docs.pytest.org/en/7.0.x/changelog.html#changelog

**Comment by ericpalakovichcarr** [comment]
Thanks, but this plugin isn't going to support pytest 7.x.  See first paragraph in README: https://github.com/ericpalakovichcarr/pytest-pythonpath#pytest-pythonpath

**Comment by barseghyanartur** [comment]
@ericpalakovichcarr:

Just stopped by to show my gratitude.

Thanks for your work on this package. I used it in many projects. Fortunately, no longer (one less dep to manage/think-about) starting from `pytest` 7.x.

Best regards. :)
